---
title: "9/20일 우천대응 CRM 분석"
author: "노윤지"
date: "2023-09-21"
output:
  html_document:
    margin:
      top: 0cm
      bottom: 0cm
      left: 0cm
      right: 0cm
---

```{r env, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warnings= FALSE)
library(tidyverse)
library(knitr)
library(gtsummary)
library(labelled)
library(summarytools)
library(kableExtra)
library(magrittr)
library(pander)
library(haven)
```

```{r,warning = FALSE, message = FALSE}
source("/Users/yj.noh/Documents/GitHub/prj-ML-model-LT_OV30/crm_weather.R")
```

###  **[Table 1.1] **Summary of crm effect analysts** {.tabset}
#### ***[A그룹]***
```{r, warning=FALSE, message=FALSE}
theme_gtsummary_compact()  
df_A  %>% tbl_strata(
    strata = is_react,~.x  %>% 
    tbl_summary(
        by = is_check,
        type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels() 
)
```

#### ***[B그룹]***
```{r, warning=FALSE, message=FALSE}
  
df_B  %>% tbl_strata(
    strata = is_react,~.x  %>% 
    tbl_summary(
        by = is_check,
        type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels() 
  )

```

#### ***[C그룹]***
```{r, warning=FALSE, message=FALSE}
  
df_C  %>% tbl_strata(
    strata = is_react,~.x  %>% 
    tbl_summary(
        by = is_check,
        type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels()
)

```
#### ***[D그룹]***
```{r, warning=FALSE, message=FALSE}
  
df_D  %>% tbl_strata(
    strata = is_react,~.x  %>% 
    tbl_summary(
        by = is_check,
        type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(1, 2), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels()
)

```