---
title: "crm effect"
author: "노윤지"
date: "2023-07-18"
output:
  html_document:
    margin:
      top: 0cm
      bottom: 0cm
      left: 0cm
      right: 0cm
---

```{r env, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warnings= FALSE)
library(tidyverse)
library(knitr)
library(gtsummary)
library(labelled)
library(summarytools)
library(kableExtra)
library(magrittr)
library(pander)
library(haven)
```

```{r,warning = FALSE, message = FALSE}
source("/Users/yj.noh/Documents/GitHub/CRM-effect-analyst-/crm_target_rider_analysis.R")
```

###  **[Table 1.1] **Summary of crm effect analysts** {.tabset}
#### ***[CRM 그룹별]***
```{r, warning=FALSE, message=FALSE}
  
data_filter <- data_filter[c("day_diff", "time_1", "n_time1", "time_2", "n_time2", "time_3", "n_time3", "time_4", "n_time4", "time_5", "n_time5","count", "auto_sum", "single_type", "group_name")]

var_label(data_filter) <- list(day_diff = "운행시간(첫배차~마지막배차)", time_1 = "오전타임", 
                               time_2 = "점심피크", time_3 = "오프피크", time_4 = "저녁피크", 
                               time_5 = "야간타임", count = "전체수행건수", auto_sum = "AI배차수행건수", 
                               single_type = "단건배달수행건수", n_time1 = "오전타임 수행 인원수", 
                               n_time2 = "점심피크 수행 인원수", n_time3 = "오프피크 수행 인원수",
                               n_time4 = "저녁피크 수행 인원수", n_time5 = "야간타임 수행 인원수")

data_filter %>% 
  tbl_summary(
    by = group_name,
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
    missing_text = "(Missing value)", 
    digits = list(all_continuous() ~ c(1, 2), 
                  all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels()

```



