---
title: "app push test/cotrol analysis"

author: "노윤지"
date: "2023-11-28"
output: html_document
---

```{r env, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warnings= FALSE)
library(tidyverse)
library(knitr)
library(gtsummary)
library(labelled)
library(summarytools)
library(kableExtra)
library(magrittr)
```

```{r,warning = FALSE, message = FALSE}
#setwd("C:/Users/Owner/Documents/GitHub/CRM-effect-analyst-")
source("AppPush.R")
```

```{r}
theme_gtsummary_compact()
```

### **[Table 1] **실험군/대조군 비교 분석** {.tabset}
#### **[실험군vs대조군]**
```{r}
df[c("crm_group", "ord_cnt", "is_logon", "is_dlvry", "cluster", "is_churn", "risk_ratio")] %>% 
tbl_summary(
    by = crm_group,
   type = list(
    ord_cnt ~ "continuous2",
    risk_ratio ~ "continuous2"
   ),  
    statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
    missing_text = "(Missing value)", 
    digits = list(all_continuous() ~ 2, all_categorical() ~ c(0, 1))
  ) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels()
```

#### **[실험군vs대조군 by 이탈여부]**
```{r}
df[c("crm_group", "ord_cnt", "is_logon", "is_dlvry", "cluster", "is_churn", "risk_ratio")] %>% 
  tbl_strata(
    strata = is_churn,
    ~ .x %>% 
tbl_summary(
    by = crm_group,
   type = list(
    ord_cnt ~ "continuous2",
    risk_ratio ~ "continuous2"
   ),  
    statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
    missing_text = "(Missing value)", 
    digits = list(all_continuous() ~ 2, all_categorical() ~ c(0, 1))
  ) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels()
)
```

#### **[실험군vs대조군 by cluster]**
```{r}
df[c("crm_group", "ord_cnt", "is_logon", "is_dlvry", "cluster", "is_churn", "risk_ratio")] %>% 
  tbl_strata(
    strata = cluster,
    ~ .x %>% 
tbl_summary(
    by = crm_group,
   type = list(
    ord_cnt ~ "continuous2",
    risk_ratio ~ "continuous2"
   ),  
    statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
    missing_text = "(Missing value)", 
    digits = list(all_continuous() ~ 2, all_categorical() ~ c(0, 1))
  ) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels()
)
```
